language: rust
env:
  global:
    - REPO=yarner-block-links

os:
  - linux

rust:
  - stable

branches:
  only:
    - master
    - "/^\\d+\\.\\d+\\.\\d+/"

script:
  - rustup component add rustfmt clippy
  - cargo fmt -- --check
  - cargo clippy --all-targets -- --deny warnings
  - cargo test --verbose
