[package]
name = "yarner-block-links"
version = "0.1.0"
authors = ["Martin Lange <martin.lange@ufz.de>"]
edition = "2018"

[dependencies]
yarner-lib = { git = "https://github.com/mlange-42/yarner.git", rev = "54488e6" }
